apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: expense
  labels:
    project: expense
    component: frontend
    tier: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      project: expense
      component: frontend
      tier: frontend
  template:
    metadata:
      labels:
        project: expense
        component: frontend
        tier: frontend
    spec:
      containers:
        - name: frontend
          image: cekharch/frontend:v3.0
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: expense
  labels:
    project: expense
    component: frontend
    tier: frontend
spec:
  type: LoadBalancer
  selector:
    project: expense
    component: frontend
    tier: frontend
  ports:
    - name: frontend
      port: 80
      targetPort: 80
