apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-configmap
  namespace: expense
  labels:
    project: expense
    component: mysql
    tier: db
data:
  DB_HOST: "mysql"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    project: expense
    component: mysql
    tier: db
spec:
  replicas: 3
  selector:
    matchLabels:
      project: expense
      component: mysql
      tier: db
  template:
    metadata: 
      labels:
        project: expense
        component: mysql
        tier: db
    spec:
      containers:
        - name: backend
          image: cekharch/backend:v7
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: backend-configmap
                  value: DB_HOST
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: expense
  labels:
    project: expense
    component: mysql
    tier: db
spec:
  selector:
    project: expense
    component: mysql
    tier: db
  ports:
    - name: backend
      port: 8080
      targetPort: 8080

