apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-configmap
  namespace: expense
  labels:
    project: expense
    component: backend
    tier: backend
data:
  DB_HOST: "mysql"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    project: expense
    component: backend
    tier: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      project: expense
      component: backend
      tier: backend
  template:
    metadata: 
      labels:
        project: expense
        component: backend
        tier: backend
    spec:
      containers:
        - name: backend
          image: cekharch/backend:v7
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: backend-configmap
                  key: DB_HOST
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: expense
  labels:
    project: expense
    component: backend
    tier: backend
spec:
  selector:
    project: expense
    component: backend
    tier: backend
  ports:
    - name: backend
      port: 8080
      targetPort: 8080

