apiVersion: v1
kind: Service
metadata:
  name: mysql-headless
  namespace: expense
  labels:
    env: prod
    component: mysql
    tier: db
spec:
  clusterIP: None
  selector:
    env: prod
    component: mysql
    tier: db
  ports:
    - name: mysql-headless
      port: 3306
      targetPort: 3306

---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: expense
  labels:
    env: prod
    component: mysql
    tier: db
spec:
  selector:
    env: prod
    component: mysql
    tier: db
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: expense
  labels:
    env: prod
    component: mysql
    tier: db
spec:
  replicas: 2
  selector:
    matchLabels:
      env: prod
      component: mysql
      tier: db
  serviceName: mysql-headless
  template:
    metadata:
      labels:
        env: prod
        component: mysql
        tier: db
    containers:
      - name: mysql
        image: cekharch/mysql:v7
        volumeMounts:
          - name: ebs-dynamic-cliam
            mountPath: /var/lib/mysql
  volumeClaimTemplates:
    - metadata:
        name: ebs-dynamic-cliam
      spec:
        storageClassName: "ebs-sc"
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            capacity: 1Gi

