apiVersion: v1
kind: Service
metadata:
  name: mysql-headless
  namespace: expense
spec:
  clusterIP: None
  selector:
    env: prod
    component: mysql
    tier: db
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: expense
spec:
  selector:
    env: prod
    component: mysql
    tier: db
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: expense
spec:
  replicas: 2
  selector:
    matchLabels:
      env: prod
      component: mysql
      tier: db
  serviceName: "mysql-headless"
  template:
    metadata:
      labels:
        env: prod
        component: mysql
        tier: db
    spec:
      containers:
        - name: mysql
          image: cekharch/mysql:v7
          volumeMounts:
            - name: mysql
              mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: mysql
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "expense-sc"
      resources:
        requests:
          storage: 1Gi

